# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8225f3566ea69d9ae0def34be9334e52f0f9bb3b6e3994a6101ec21529b189377f682fd4f0939f89e005dab3b737e5f3cbc83ce4ac78f11b3fdd0b10bda876bc

test:
  secret_key_base: 9d9512ad530389e1ad8f8c35f9d6f386c22ac874d1cbe97796757673971c6dcc22d387d790e365a840d03cdaad1e397ec7a4bf55c87721507dd4bb3d2591e44e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
